apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: joke-replicaset
  labels:
      app: fast-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fast-api
  template:
    metadata:
      name: pp1
      labels:
          app: fast-api
    spec:
      containers:
      - name: joker-app
        image: 192.168.49.2:5000/jokes1:latest
        ports:
        - containerPort: 8083
